init = '===== Initializing ====='
initdone = '===== Initialized ====='
wintitle = 'Google-o-funirator'
result = 'Result:'
ttt = "Text To Translate"
netspeednote = 'Translation Speed Depend On your internet speed'
title = 'Google-o-funirator'
tr = '===== Traslation start ====='
trdone = '===== translation done. ====='
trlog = 'Translating to '
googlebannotice = 'Looks like you were banned by google :/'
etcexception = 'Something happened'
